name: Greeting from Keith

on: 
  push:
    branches: [master]

  pull_request:
    branches: [master]

  workflow_dispatch
jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Print a greeting
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Ho Kong
        MIDDLE_NAME: _
        LAST_NAME: Lee
      run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
